apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: bretfisher/examplevotingapp_worker:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"