apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 5432
    name: db-service
    targetPort: 5432

# kubectl create -f services/ --save-config --record

# Criação dos serviços