apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - port: 5000
    name: vote-service
    targetPort: 80
    nodePort: 31000
